### ISSUE TITLE
Is this repo still maintained? 

### ISSUE THREAD

**Issue by reshadf** [sandermarechal/jejik-mt940#20]
Hi is this repo still maintained? I would like to use it or even convert it to a laravel library but I see that the last commit is from 2014. @sandermarechal

**Comment by stefanneubig** [comment]
I can say that we use it sucessfully in production. Also within a laravel app. 

It could be that there just isn't much to maintain...

**Comment by stefanneubig** [comment]
@przemekperon

**Comment by reshadf** [comment]
Oh thanks for the heads up, Do you have ported it to laravel or are you just using it like this? @stefanneubig

**Comment by przemekperon** [comment]
@reshadf we do use it with the latest Laravel 5.4 without any modifications in the way it's described in the documentation.

**Comment by sandermarechal** [comment]
I am not really maintaining this library anymore. The project I was using this for never took off so I don't really have a need. I'd be happy to grant other people commit rights if they want to maintain this library. The base is pretty solid. Most of the work would probably be adding support for other banks.

As for using it in Laravel, you can just write the Laravel package in a separate repo and add this library as a composer dependency. It's usually a good idea to keep the code library functions and the framework integration separate.

**Comment by InVeX** [comment]
Agree with @sandermarechal . I am using this library with ZF2 and it works just perfect. Framework integrations are better to do in a separate repos. Thank You!

**Comment by NanneHuiges** [comment]
@sandermarechal If you still are looking for extra hands I wouldn't mind helping out with maintaining in these cases? 

I'd like to see https://github.com/sandermarechal/jejik-mt940/pull/23 merged, and willing to help :)

**Comment by sandermarechal** [comment]
I'm happy to review, test and merge PRs. It's mainly adding new banks that I don't really have the time for. PRs are always welcome!

**Comment by NanneHuiges** [comment]
Ow cool, thanks!

**Comment by twitnic** [comment]
@sandermarechal We are still considering internally what the best solution is to take over the repo. Namespace, Repo-Name, ...
But in the meantime, we could still close this issue, couldn't we?

**Comment by sandermarechal** [comment]
Yup, agreed.
