### ISSUE TITLE
'RuntimeException' with message 'No suitable parser found.'

### ISSUE THREAD

**Issue by websafe** [sandermarechal/jejik-mt940#26]
Hello.

I'm trying to understand how to use this parser, so I'm not sure if it's me or my MT940 file's fault ;-)
My `sta` file is from ING (Poland).

I've tried this:

```php
<?php
require 'vendor/autoload.php';
use Jejik\MT940\Reader;

$mt940file = 'test.sta';
$reader = new Reader();
var_dump($reader->getParsers());
$reader->setParsers(array('ING' => 'Jejik\MT940\Parser\Ing'));
var_dump($reader->getParsers());

$statements = $reader->getStatements(file_get_contents($mt940file));
foreach ($statements as $statement) {
  echo $statement->getOpeningBalance()->getAmount() . "\n";
  foreach ($statement->getTransactions() as $transaction) {
    echo $transaction->getAmount() . "\n";
  }
  echo $statement->getClosingBalance()->getAmount() . "\n";
}
```

But all I get is:

```console
array(0) {
}
array(1) {
  ["ING"]=>
  string(22) "Jejik\MT940\Parser\Ing"
}
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'No suitable parser found.' in /tmp/mt940-2/vendor/jejik/mt940/lib/Jejik/MT940/Reader.php:489
Stack trace:
#0 /tmp/mt940-2/index.php(17): Jejik\MT940\Reader->getStatements(':20:MT940\r\n:25:...')
#1 {main}
  thrown in /tmp/mt940-2/vendor/jejik/mt940/lib/Jejik/MT940/Reader.php on line 489
```

Did I forget something or is it something with my `test.sta`?

**Comment by sandermarechal** [comment]
The file format may have changed. Can you share the first line from your STA file? The files used to start like this:

```
{1:F01INGBNL2AXXXX00001}
```
The ING parser specifically looks for the string `INGBNL` or it will refose to parse the file.

**Comment by websafe** [comment]
Hello @sandermarechal 

My sta begins with:

```
:20:MT940
:25:/PL12345678912345678912345678
:28C:9
:60F:C190930PLN66666,66
:61:1909020902D850,39S02097202028342
:86:020
:86:020~00IBCG
```

and the official docs for MT940 used by ING-PL (ING-BSK) are located here: https://www.ing.pl/_fileserver/item/1003276

**Comment by sandermarechal** [comment]
That appears to be a different format than the ING bank uses in The Netherlands. Your file appears to be just a raw MT940 file, while the Dutch version embeds the raw MT940 code inside a carrier format that uses curly braces as a delimiter.

I think you are better off implementing a custom parser for your file. Start out using the `AbstractParser` which can parse most of the standard MT940 files. Then see if it needs tweaking by overriding some of the methods. Looking at your documentation it appears that the description field contains many ING-PL specific subfields marked with ~ signs. You could try adding support for those as well.
