### ISSUE TITLE
Setting a custom Statement class is broken in php 7.4 and upwards

### ISSUE THREAD

**Issue by faustimetal** [sandermarechal/jejik-mt940#46]
Because statementBody has a return type of Statement, you can't use a custom Statement class, because it will error saying that "CustomStatementClassX is not Statement".

This was fixed in a previous release, but reverted yesterday because it broke compability with EOL php version 7.3.

To enable it in all version you have to remove the return type completely. To reenable support for php 7.4 and upwards you have to reinstate the interface as the return type.

**Comment by twitnic** [comment]
Merged. And in Version 0.6.0 released.
