### ISSUE TITLE
SEPA/IBAN consequences

### ISSUE THREAD

**Issue by scspruijt** [sandermarechal/jejik-mt940#7]
Hi,

I've been using your parser and it is by far the best structured parser out there, thanks for that. I was just wondering if you're planning to update the parser to accomodate the new SEPA/IBAN changes. I've been trying to make some changes to the parser myself, but I'm sure I'll break more than I'll fix.

Thanks for considering.

Regards,
Sander Spruijt

**Comment by tswestendorp** [comment]
I have a test file for ING, hope it helps solving this issue. Looking forward to IBAN-support

@sandermarechal, I'll e-mail the file to your personal address shortly.

**Comment by pruimmartin** [comment]
@sandermarechal any news on the ING IBAN-support? Looking forward to it!

**Comment by sirdiego** [comment]
Hey @tswestendorp, maybe you can clean up the test file and upload it here? I could have a quick look and create a MR if it's easy enough :see_no_evil:

**Comment by tswestendorp** [comment]
Looks like I'm only able to add images, so here's an archive containing a TXT and PDF file 
https://www.wetransfer.com/downloads/bbf3e201c175599a2011a7bed276abcf20150119192751/223f17c4cf80f286ada3607c7b12bee220150119192751/5e422f

**Comment by peitjeloos** [comment]
ING IBAN-support is pritty easy, in the file MT940/Parser/Ing.php line 30
Replace
return substr($text, 7, 6) === 'INGBNL';
to 
return substr($text, 6, 6) === 'INGBNL';

Good luck.

**Comment by sandermarechal** [comment]
I have fixed the ING parser
